[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
src = ["backend/app"]
target-version = "py311"
line-length = 100
exclude = ["backend/migrations"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "C4", "SIM", "RUF"]
# Ignora E501 para que la longitud la gobierne Black
ignore = ["E203", "E501"]

[tool.ruff.format]
# Si usas Black como formateador principal, puedes omitir esta sección o dejarla (no interfiere).
quote-style = "preserve"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
