"""add cycle model

Revision ID: 1a15b65afbd0
Revises: 862e6258b903
Create Date: 2025-10-02 18:58:55.002685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a15b65afbd0'
down_revision = '862e6258b903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cycle_number > 0', name='ck_cycles_number_positive'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'cycle_number', name='uq_cycles_routine_number')
    )
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.create_index('ix_cycles_routine', ['routine_id'], unique=False)
        batch_op.create_index('ix_cycles_user_started_on', ['user_id', 'started_on'], unique=False)

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_ws_cycle', ['cycle_id'], unique=False)
        batch_op.create_foreign_key('fk_ws_cycle_id', 'cycles', ['cycle_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ws_cycle_id', type_='foreignkey')
        batch_op.drop_index('ix_ws_cycle')
        batch_op.drop_column('cycle_id')

    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.drop_index('ix_cycles_user_started_on')
        batch_op.drop_index('ix_cycles_routine')

    op.drop_table('cycles')
    # ### end Alembic commands ###
