"""add fitness tracking models

Revision ID: ea08a54b2628
Revises: 2c7a5605bbd9
Create Date: 2025-09-30 18:31:23.789861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea08a54b2628'
down_revision = '2c7a5605bbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'BICEPS', 'TRICEPS', 'CALVES', 'ABS', 'FULL_BODY', 'OTHER', name='musclegroup'), nullable=False),
    sa.Column('is_unilateral', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_muscle_group'), ['muscle_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=True)

    op.create_table('routines',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routines_user_id'), ['user_id'], unique=False)

    op.create_table('routine_exercises',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('rest_sec', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'order', name='uq_routine_order')
    )
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routine_exercises_routine_id'), ['routine_id'], unique=False)

    op.create_table('workouts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_routine_id'), ['routine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_user_id'), ['user_id'], unique=False)

    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'order', name='uq_workout_order')
    )
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_exercises_workout_id'), ['workout_id'], unique=False)

    op.create_table('workout_sets',
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Float(), nullable=True),
    sa.Column('time_sec', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_exercise_id', 'set_index', name='uq_workout_set_index')
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_workout_exercise_id'), ['workout_exercise_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('name')

    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_workout_exercise_id'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_exercises_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_exercises_exercise_id'))

    op.drop_table('workout_exercises')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_user_id'))
        batch_op.drop_index(batch_op.f('ix_workouts_routine_id'))
        batch_op.drop_index(batch_op.f('ix_workouts_date'))

    op.drop_table('workouts')
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_exercises_routine_id'))
        batch_op.drop_index(batch_op.f('ix_routine_exercises_exercise_id'))

    op.drop_table('routine_exercises')
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routines_user_id'))

    op.drop_table('routines')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_muscle_group'))

    op.drop_table('exercises')
    # ### end Alembic commands ###
